name: Terraform Deploy

on:
  push:
    branches:
      - master

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: af-south-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: iac
        run: terraform init

      - name: Terraform Validate
        working-directory: iac
        run: terraform validate

      - name: Terraform Plan
        working-directory: iac
        env:
          TF_VAR_ec2_public_key: ${{ secrets.EC2_PUBLIC_KEY }}
        run: terraform plan
      
      - name: Terraform Apply
        working-directory: iac
        env:
        TF_VAR_ec2_public_key: ${{ secrets.EC2_PUBLIC_KEY }}
        run: |
          terraform init
          terraform apply -auto-approve
        
     # - name: Terraform Destroy
      #  working-directory: iac
       # env:
        #  TF_VAR_ec2_public_key: ${{ secrets.EC2_PUBLIC_KEY }}
        #run: |
         # terraform init
          #terraform destroy -auto-approve    